# Generated by Django 4.0.1 on 2022-02-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
