# Generated by Django 4.0.1 on 2022-02-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_commentlike_comment_alter_commentlike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment',
            new_name='commentId',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='user',
            new_name='userId',
        ),
    ]
