# Generated by Django 4.0.1 on 2022-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_postvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalVote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='downVote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
