# Generated by Django 4.0.1 on 2022-03-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_post_downvote_remove_post_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='totalVote',
        ),
    ]
