# Generated by Django 4.0.1 on 2022-08-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_post_totalvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subribbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('ownerId', models.IntegerField(blank=True, null=True)),
                ('numMembers', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubribbitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('subribbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subribbit')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='subribbit',
            name='members',
            field=models.ManyToManyField(through='base.SubribbitMember', to='base.UserProfile'),
        ),
    ]
