# Generated by Django 4.1 on 2022-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_subribbit_subribbitmember_subribbit_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='subribbit',
            name='type',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
