# Generated by Django 4.1 on 2022-12-11 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_post_numcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subribbit',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
