# Generated by Django 4.1.3 on 2022-12-15 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_userprofile_numcomments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='numComments',
        ),
    ]
