# Generated by Django 4.1.3 on 2022-12-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userName',
        ),
    ]
