# Generated by Django 4.1 on 2022-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resetToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resetTokenTime',
            field=models.DateTimeField(null=True),
        ),
    ]
