# Generated by Django 4.1.3 on 2023-01-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_userprofile_resettoken_userprofile_resettokentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subribbit',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
